package com.labteto.dshmobile.ui.screens.local

internal const val MAX_PERSONA_PORTRAIT_BYTES = 20L * 1024L * 1024L
internal const val LOCAL_TRANSCRIPT_HISTORY_PAGE_MESSAGES = 200
internal const val LOCAL_TRANSCRIPT_INITIAL_VISIBLE_DIALOGUE_MESSAGES = 200
internal const val LOCAL_TRANSCRIPT_HISTORY_VISIBLE_DIALOGUE_BATCH_MESSAGES = 40
internal const val PERSONA_INSPECTION_RECENT_MESSAGES = 28
internal const val PERSONA_AUTOFILL_RECENT_MESSAGES = 12
